#
# This is LyTreeHelper's main configuration file
#
# This is the global configuration file. This file contains the global
# settings and default settings for all your worlds. You can configure each
# setting for each world in its own configuration file to allow you to
# replace most settings in here for that world only. Same for the
# schematic settings.
#
# About editing this file:
# - DO NOT USE TABS. You MUST use spaces or Bukkit will complain. If
# you use an editor like Notepad++ (recommended for Windows users), you
# must configure it to "replace tabs with spaces." In Notepad++, this can
# be changed in Settings > Preferences > Language Menu.
# - Don't get rid of the indents. They are indented so some entries are
# in categories (like "max-tree-size" is in the "system"
# category.
# - If you want to check the format of this file before putting it
# into WorldGuard, paste it into http://yaml-online-parser.appspot.com/
# and see if it gives "ERROR:".
# - Lines starting with # are comments and so they are ignored.
#

system:
    # Should LyTreeHelper show the config for this world if the world is loading?
    show-config-on-start: false

    # Should LyTreeHelper add a log entry in the console if a player triggers a command?
    show-commands-in-log: true

    # WARNING! Setting this option to on will enable a maximum tree size of 6000 instead of 1800.
    # WARNING! If your craftbukkit setup isn't running with enough RAM for this option, it will
    # WARNING! cause many errors and force an server restart!
    # WARNING! This option is only for experienced users!
    enable-high-stack-size: false

    # Sets the maximum tree size. can be an integer from 0 to 1800.
    max-tree-size: 1600

    # The max. radius which can a tree have. This makes it possible to chop single trees in forests.
    # Set the max. tree radius to 0 to enable an endless radius.
    # This setting can be an integer from 0 to 50.
    max-tree-radius: 5

default-world-configuration:
    # Enables or disables auto planting of an sapling on full destruction or full wood destruction only.
    enable-autoplant-sapling: true
    
    # Enables the custom world Populator
    enable-custom-populator: false
    
    leaves-decay:
        # Enables or disables the normal leaves decay in minecraft.
        enable-leaves-decay: true
        # Enables or disables faster decay of leaves.
        enable-faster-decay: false

    tree-destruction:
        # Let you destroy more leave-blocks at once.
        # If you enable this, you can disable it ingame by sneaking.
        enable-faster-leaves-destruction: false
        # Enables or disables the full destruction of complete trees.
        # If you enable this, you can disable it ingame by sneaking.
        enable-full-tree-destruction: true
        # Enables or disables the full destruction of the tree wood only.
        only-wood-destruction: false

    drops:
        # Leaveblocks drops their items only if the player harvests the tree from top to bottom
        # That means, the block above the harvested block must be air
        enable-only-top-down-drops: false

        # Enable apple-drops over time?
        # If enabled, LyTreeHelper will cause apple drops from trees over time.
        # Don't forget to set the drop chance!
        # "apple-drops-over-time-chance" must be a double from 0.0 to 100.0
        enable-apple-drops-over-time: true
        apple-drop-over-time-chance: 1.0

        # The following options can be a decimal number from 0.0 to 100.0
        # Use this settings to modify the drop chance of apples, golden apples, leave blocks and saplings from leaves. 
        apple-drop-chance: 1.0
        golden-apple-drop-chance: 0.1
        leaves-block-drop-chance: 5.0
        sapling-drop-chance: 8.0

        # Custom Drops
        # Custom drops must match the following mask
        #     "itemId": dropChance
        #
        # itemId is the id of the item which should be dropped.
        # dropChance can be a decimal number from 0.0 to 100.0
        #
        # Example:
        # custom-drops:
        #     "2": 10.0
        #     "3": 38.2
        #     "35,14": 5.0 //Red wool
        # Note: Remove the [] first
        custom-drops: []


    economy:
        # Should LyTreeHelper remove some money from the player's iConomy account on full destruction of a tree?
        # If set to on LyTreeHelper will remove the set amount of money from the players bank account.
        # "iconomy-money-on-full-destruction" must be a double value.
        enable-economy-support: false
        costs-on-full-destruction: 10.0

    creatures:
        # This option works only if both "enable-full-tree-destruction" and "enable-full-wood-destruction" are set to on/true.
        # If you destroy a tree, one creature in this list will spawn at the location of the destroyed tree.
        # Possible items for the list are:
        # CREEPER, SKELETON, SPIDER, GIANT, ZOMBIE, SLIME, GHAST, PIG_ZOMBIE, ENDERMAN, CAVE_SPIDER, SILVERFISH, BLAZE,
        # MAGMA_CUBE, PIG, SHEEP, COW, CHICKEN, SQUID, WOLF, MUSHROOM_COW, SNOWMAN, OCELOT, IRON_GOLEM, VILLAGER
        # Example list: creatures-to-spawn-in-trees: [PIG,COW,SPIDER]
        # If you want to change the chance of spawning a creature, use the "creature-spawn-chance" option below.
        # "creature-spawn-chance" must be a double from 0.0 to 100.0 
        creatures-to-spawn-in-trees: []
        creature-spawn-chance: 30.0

    tools:
        # Lists below this comment may match this example:
        # full-destruction-tools: [283,284,285,286]
        # An empty list means, that all tools can be used.

        # Tools which can be used for full destruction of trees.
        full-destruction-tools: []

        # Tools which can be used to harvest leave-blocks and apples.
        harvest-tools: []

    # Schematics settings for the custom populator, ignored if enable-custom-populator is set to false
    # Possible biomes are:
    # RAINFOREST, SWAMPLAND, SEASONAL_FOREST, FOREST, SAVANNA, SHRUBLAND, TAIGA, DESERT, PLAINS,
    # ICE_DESERT, TUNDRA, HELL, SKY, OCEAN, RIVER, EXTREME_HILLS, FROZEN_OCEAN, FROZEN_RIVER,
    # ICE_PLAINS, ICE_MOUNTAINS, MUSHROOM_ISLAND, MUSHROOM_SHORE, BEACH, DESERT_HILLS, FOREST_HILLS
    # TAIGA_HILLS, SMALL_MOUNTAINS, JUNGLE, JUNGLE_HILLS
    # The biome list is a string list which may match this examples:
    # [FOREST,RAINFOREST,SEASONAL_FOREST]   or   [BEACH]
    # The chances must be a double from 0.0 to 100.0
    schematics:
        SmallPalm:
            biomes: [BEACH]
            chance: 30.0
        TallPalm:
            biomes: [BEACH]
            chance: 10.0
        TallBirch:
            biomes: [FOREST, SEASONAL_FOREST]
            chance: 5.0